# Generated by Django 4.1a1 on 2022-05-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_first_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="bio",),
        migrations.RemoveField(model_name="user", name="gender",),
        migrations.RemoveField(model_name="user", name="language",),
        migrations.AddField(
            model_name="user",
            name="superhost",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars"),
        ),
    ]
